apiVersion: v2
name: scalardb-analytics-server
description: ScalarDB Analytics Server
type: application
version: 1.1.2
appVersion: 3.17.1
deprecated: false
icon: https://scalar-labs.com/wp-content/themes/scalar/assets/img/logo_scalar.svg
keywords:
- scalardb-analytics
- scalardb-analytics-server
- analytics
- grpc
- grpc-server
home: https://scalar-labs.com/
sources:
  - https://github.com/scalar-labs/scalardb-analytics
maintainers:
  - name: Takanori Yokoyama
    email: takanori.yokoyama@scalar-labs.com
