{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.scalardb.serviceMonitor.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "scalardb.fullname" . }}-metrics
{{- if .Values.scalardb.serviceMonitor.namespace }}
  namespace: {{ .Values.scalardb.serviceMonitor.namespace }}
{{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "scalardb.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: scalardb-server-prometheus
    interval: {{ .Values.scalardb.serviceMonitor.interval }}
{{- end }}
