apiVersion: v2
name: scalar-manager
description: Scalar Manager
type: application
version: 3.0.1
appVersion: 3.0.1
deprecated: false
icon: https://scalar-labs.com/wp-content/themes/scalar/assets/img/logo_scalar.svg
keywords:
  - scalar-manager
  - scalardb-cluster
  - scalardl-ledger
  - scalardl-auditor
  - scalar-admin-for-kubernetes
home: https://scalar-labs.com/
sources:
  - https://github.com/scalar-labs/scalar-manager-api
  - https://github.com/scalar-labs/scalar-manager-web
maintainers:
  - name: Takanori Yokoyama
    email: takanori.yokoyama@scalar-labs.com
  - name: Plenty Su
    email: plenty.su@scalar-labs.com
