apiVersion: v2
name: scalardl
description: ScalarDL is a tamper-evident and scalable distributed database.
type: application
version: 4.9.5
appVersion: 3.10.4
deprecated: false
icon: https://scalar-labs.com/wp-content/themes/scalar/assets/img/logo_scalar.svg
keywords:
- "database"
- "distributed ledger"
- "scalar"
- "scalardl"
home: https://scalar-labs.com/
sources:
  - https://github.com/scalar-labs/scalardl
dependencies:
- name: envoy
  version: ~2.6.0
  repository: https://scalar-labs.github.io/helm-charts
  condition: envoy.enabled
maintainers:
  - name: Takanori Yokoyama
    email: takanori.yokoyama@scalar-labs.com
  - name: Hiroyuki Yamada
    email: hiroyuki.yamada@scalar-labs.com
