apiVersion: v2
name: scalardb-cluster
description: ScalarDB Cluster
type: application
version: 2.0.0-SNAPSHOT
appVersion: 4.0.0-SNAPSHOT
kubeVersion: ">= 1.31.0"
deprecated: false
icon: https://scalar-labs.com/wp-content/themes/scalar/assets/img/logo_scalar.svg
keywords:
- scalardb
- scalardb-cluster
- grpc
- grpc-server
home: https://scalar-labs.com/
sources:
  - https://github.com/scalar-labs/scalardb-cluster
dependencies:
- name: envoy
  version: ~3.0.0-SNAPSHOT
  repository: file://../envoy/
  condition: envoy.enabled
maintainers:
  - name: Takanori Yokoyama
    email: takanori.yokoyama@scalar-labs.com
annotations:
  charts.openshift.io/name: "ScalarDB Cluster Helm Chart"
