apiVersion: v2
name: scalardb-mcp-server
description: ScalarDB MCP Server
type: application
version: 1.0.0-SNAPSHOT
appVersion: 1.0.0-SNAPSHOT
deprecated: false
icon: https://scalar-labs.com/wp-content/themes/scalar/assets/img/logo_scalar.svg
keywords:
  - scalardb-mcp-server
  - scalardb
home: https://scalar-labs.com/
sources:
  - https://github.com/scalar-labs/scalardb-mcp-server
maintainers:
  - name: Pham Ba Thong
    email: thong.pham@scalar-labs.com
  - name: Takanori Yokoyama
    email: takanori.yokoyama@scalar-labs.com
