apiVersion: v2
name: schema-loading
description: Implementation schema loading for scalar-ledger
type: application
version: 2.0.1
appVersion: 3.0.0
deprecated: false
icon: https://scalar-labs.com/wp-content/themes/scalar/assets/img/logo_scalar.svg
keywords:
- scalar-ledger
- DLT
- schema-loading
home: https://scalar-labs.com/
sources:
  - https://github.com/scalar-labs/scalardb/tree/master/tools/scalar-schema
maintainers:
  - name: Paul Dozancuk
    email: paul.dozancuk@scalar-labs.com
  - name: Yusuke Morimoto
    email: yusuke.morimoto@scalar-labs.com
