apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalardb-mcp-server.fullname" . }}-application-properties
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardb-mcp-server.labels" . | nindent 4 }}
data:
  application.properties: |
    {{- .Values.scalardbMcpServer.applicationProperties | nindent 4 }}
