{{- if not .Values.scalardbMcpServer.serviceAccount.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scalardb-mcp-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardb-mcp-server.labels" . | nindent 4 }}
{{- end }}
