{{- if .Values.envoy.grafanaDashboard.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalardl.fullname" . }}-envoy-grafana-dashboard
  labels:
    grafana_dashboard: "1"
    {{- include "scalardl-envoy.labels" . | nindent 4 }}
{{- if .Values.envoy.grafanaDashboard.namespace }}
  namespace: {{ .Values.envoy.grafanaDashboard.namespace }}
{{- end }}
data:
{{- range $path, $_ :=  .Files.Glob  "files/grafana/envoy_*.json" }}
  {{ $path | base }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
